version: "3.7"
services:
    microservice_rabbitMQ:
        build:
            args:
                user: rockske8er
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microservices

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    db_ms_rabbitMQ:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/db/:/var/lib/mysql
        ports:
            - 3308:3306
        networks:
            - microservices

networks:
    microservices:
        driver: bridge
